# Generated by Django 2.1.5 on 2019-02-12 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='debts',
            fields=[
                ('T_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('reciever', models.CharField(max_length=264)),
                ('remarks', models.CharField(max_length=264)),
                ('Deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='general_expenses',
            fields=[
                ('T_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('category', models.IntegerField(choices=[(1, 'Food9'), (2, 'Travel'), (3, 'Groceries'), (4, 'Electronics'), (5, 'Clothing or Footwear'), (6, 'Household shopping'), (7, 'Other- specify in remarks')])),
                ('remarks', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='mandatory_expenses',
            fields=[
                ('T_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('category', models.IntegerField(choices=[(1, 'Food9'), (2, 'Travel'), (3, 'Groceries'), (4, 'Electronics'), (5, 'Clothing or Footwear'), (6, 'Household shopping'), (7, 'Other- specify in remarks')])),
                ('remarks', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('Email', models.EmailField(max_length=264, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=264)),
                ('LastName', models.CharField(max_length=264)),
                ('Password', models.CharField(max_length=264)),
                ('PhoneNo', models.IntegerField()),
                ('Wallet', models.IntegerField()),
                ('frequent_wallet_addition_amount', models.IntegerField()),
                ('amount_to_be_added', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mandatory_expenses',
            name='Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analyzer.user_profile'),
        ),
        migrations.AddField(
            model_name='general_expenses',
            name='Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analyzer.user_profile'),
        ),
        migrations.AddField(
            model_name='debts',
            name='Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analyzer.user_profile'),
        ),
    ]
