# Generated by Django 2.1.5 on 2019-03-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debts',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='general_expenses',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='general_expenses',
            name='category',
            field=models.IntegerField(choices=[(1, 'Food'), (2, 'Travel'), (3, 'Groceries'), (4, 'Electronics'), (5, 'Clothing or Footwear'), (6, 'Household shopping'), (7, 'Other- specify in remarks')]),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
